/**
 * Career Catalog
 * 
 * Curated list of 30 careers with metadata for Explorer Mode unlocks.
 * 
 * @module lib/career-catalog
 */

export interface CareerData {
  id: string;
  title: string;
  shortPitch: string;
  dayInLife: string;
  skillSignals: string[];
  recommendedSubjects: string[];
  starterPathSteps: string[];
  icon: string;
  rarityTier: 'COMMON' | 'EMERGING' | 'ADVANCED' | 'FRONTIER';
}

export const CAREER_CATALOG: CareerData[] = [
  {
    id: 'software_engineer',
    title: 'Software Engineer',
    shortPitch: 'Build digital solutions that solve real-world problems',
    dayInLife: 'Start your day reviewing code, collaborate with your team on new features, debug issues, and design elegant solutions. You might spend the afternoon writing tests, attending standup meetings, and learning new technologies.',
    skillSignals: ['COGNITIVE_REASONING', 'PLANNING'],
    recommendedSubjects: ['Mathematics', 'Computer Science', 'Physics'],
    starterPathSteps: ['Learn programming basics', 'Build small projects', 'Contribute to open source'],
    icon: '💻',
    rarityTier: 'COMMON',
  },
  {
    id: 'data_scientist',
    title: 'Data Scientist',
    shortPitch: 'Turn data into insights that drive decisions',
    dayInLife: 'Analyze datasets, create visualizations, build predictive models, and present findings to stakeholders. You work with large amounts of information to find patterns and tell stories through data.',
    skillSignals: ['COGNITIVE_REASONING', 'ATTENTION'],
    recommendedSubjects: ['Mathematics', 'Statistics', 'Computer Science'],
    starterPathSteps: ['Learn statistics and programming', 'Practice with real datasets', 'Build a portfolio'],
    icon: '📊',
    rarityTier: 'COMMON',
  },
  {
    id: 'graphic_designer',
    title: 'Graphic Designer',
    shortPitch: 'Create visual experiences that communicate and inspire',
    dayInLife: 'Design logos, websites, and marketing materials. You collaborate with clients, sketch ideas, use design software, and refine your work based on feedback. Every project is a new creative challenge.',
    skillSignals: ['CREATIVITY', 'LANGUAGE'],
    recommendedSubjects: ['Art', 'Design', 'Communication'],
    starterPathSteps: ['Learn design principles', 'Master design tools', 'Build a portfolio'],
    icon: '🎨',
    rarityTier: 'COMMON',
  },
  {
    id: 'teacher',
    title: 'Teacher',
    shortPitch: 'Shape young minds and inspire lifelong learning',
    dayInLife: 'Plan lessons, teach classes, grade assignments, and support students. You adapt your teaching style to help each student learn, celebrate their progress, and create a positive classroom environment.',
    skillSignals: ['LANGUAGE', 'SOCIAL_EMOTIONAL', 'METACOGNITION'],
    recommendedSubjects: ['Education', 'Your subject area', 'Psychology'],
    starterPathSteps: ['Get a teaching degree', 'Gain classroom experience', 'Continue professional development'],
    icon: '👨‍🏫',
    rarityTier: 'COMMON',
  },
  {
    id: 'doctor',
    title: 'Doctor',
    shortPitch: 'Heal, care, and make a difference in people\'s lives',
    dayInLife: 'See patients, diagnose conditions, prescribe treatments, and provide care. You work in hospitals or clinics, collaborate with medical teams, and continuously learn about new medical advances.',
    skillSignals: ['COGNITIVE_REASONING', 'ATTENTION', 'SOCIAL_EMOTIONAL'],
    recommendedSubjects: ['Biology', 'Chemistry', 'Mathematics'],
    starterPathSteps: ['Complete pre-med studies', 'Medical school', 'Residency training'],
    icon: '👨‍⚕️',
    rarityTier: 'EMERGING',
  },
  {
    id: 'architect',
    title: 'Architect',
    shortPitch: 'Design spaces where people live, work, and play',
    dayInLife: 'Create building designs, work with clients, create blueprints, and oversee construction. You balance creativity with practical requirements, building codes, and sustainability principles.',
    skillSignals: ['CREATIVITY', 'PLANNING', 'COGNITIVE_REASONING'],
    recommendedSubjects: ['Mathematics', 'Art', 'Physics'],
    starterPathSteps: ['Study architecture', 'Complete internships', 'Get licensed'],
    icon: '🏗️',
    rarityTier: 'EMERGING',
  },
  {
    id: 'writer',
    title: 'Writer',
    shortPitch: 'Tell stories and share ideas through words',
    dayInLife: 'Research topics, write articles or books, edit your work, and collaborate with editors. You might write fiction, journalism, marketing content, or technical documentation.',
    skillSignals: ['LANGUAGE', 'CREATIVITY', 'METACOGNITION'],
    recommendedSubjects: ['English', 'Literature', 'Journalism'],
    starterPathSteps: ['Write regularly', 'Build a portfolio', 'Get published'],
    icon: '✍️',
    rarityTier: 'COMMON',
  },
  {
    id: 'psychologist',
    title: 'Psychologist',
    shortPitch: 'Understand human behavior and help people thrive',
    dayInLife: 'Conduct therapy sessions, assess clients, develop treatment plans, and research human behavior. You listen, observe, and help people understand themselves and overcome challenges.',
    skillSignals: ['SOCIAL_EMOTIONAL', 'METACOGNITION', 'ATTENTION'],
    recommendedSubjects: ['Psychology', 'Biology', 'Statistics'],
    starterPathSteps: ['Study psychology', 'Get a graduate degree', 'Complete licensure'],
    icon: '🧠',
    rarityTier: 'EMERGING',
  },
  {
    id: 'chef',
    title: 'Chef',
    shortPitch: 'Create culinary experiences that delight and nourish',
    dayInLife: 'Plan menus, prepare dishes, manage kitchen staff, and ensure quality. You experiment with flavors, follow recipes, and create new dishes. Every meal is an opportunity to create something special.',
    skillSignals: ['CREATIVITY', 'PLANNING'],
    recommendedSubjects: ['Culinary Arts', 'Chemistry', 'Business'],
    starterPathSteps: ['Culinary school or apprenticeship', 'Work in kitchens', 'Develop your style'],
    icon: '👨‍🍳',
    rarityTier: 'COMMON',
  },
  {
    id: 'engineer',
    title: 'Engineer',
    shortPitch: 'Solve complex problems and build the future',
    dayInLife: 'Design systems, analyze problems, create solutions, and test prototypes. You might work on bridges, electronics, energy systems, or software. Engineering combines creativity with technical precision.',
    skillSignals: ['COGNITIVE_REASONING', 'PLANNING', 'ATTENTION'],
    recommendedSubjects: ['Mathematics', 'Physics', 'Engineering'],
    starterPathSteps: ['Get an engineering degree', 'Complete internships', 'Get licensed'],
    icon: '⚙️',
    rarityTier: 'COMMON',
  },
  {
    id: 'musician',
    title: 'Musician',
    shortPitch: 'Express emotions and connect with audiences through music',
    dayInLife: 'Practice your instrument, compose music, perform live or record, and collaborate with other musicians. You might teach, perform, or create original compositions.',
    skillSignals: ['CREATIVITY', 'ATTENTION', 'METACOGNITION'],
    recommendedSubjects: ['Music', 'Arts', 'Performance'],
    starterPathSteps: ['Learn an instrument', 'Practice regularly', 'Perform and build audience'],
    icon: '🎵',
    rarityTier: 'COMMON',
  },
  {
    id: 'scientist',
    title: 'Scientist',
    shortPitch: 'Discover new knowledge and advance human understanding',
    dayInLife: 'Design experiments, collect data, analyze results, and publish findings. You work in labs or field settings, collaborate with other researchers, and contribute to scientific knowledge.',
    skillSignals: ['COGNITIVE_REASONING', 'ATTENTION', 'PLANNING'],
    recommendedSubjects: ['Your field of science', 'Mathematics', 'Statistics'],
    starterPathSteps: ['Get a science degree', 'Complete research projects', 'Publish findings'],
    icon: '🔬',
    rarityTier: 'EMERGING',
  },
  {
    id: 'lawyer',
    title: 'Lawyer',
    shortPitch: 'Advocate for justice and help people navigate legal systems',
    dayInLife: 'Research cases, write legal documents, meet with clients, and argue in court. You analyze complex information, build arguments, and help people understand their rights and options.',
    skillSignals: ['LANGUAGE', 'COGNITIVE_REASONING', 'PLANNING'],
    recommendedSubjects: ['English', 'History', 'Political Science'],
    starterPathSteps: ['Get a law degree', 'Pass the bar exam', 'Gain experience'],
    icon: '⚖️',
    rarityTier: 'EMERGING',
  },
  {
    id: 'entrepreneur',
    title: 'Entrepreneur',
    shortPitch: 'Build businesses and turn ideas into reality',
    dayInLife: 'Plan business strategies, meet with investors, manage teams, and solve problems. You wear many hats, take calculated risks, and work to grow your business while learning from setbacks.',
    skillSignals: ['CREATIVITY', 'PLANNING', 'SOCIAL_EMOTIONAL'],
    recommendedSubjects: ['Business', 'Economics', 'Your passion area'],
    starterPathSteps: ['Identify a problem', 'Build a solution', 'Launch and iterate'],
    icon: '🚀',
    rarityTier: 'ADVANCED',
  },
  {
    id: 'veterinarian',
    title: 'Veterinarian',
    shortPitch: 'Care for animals and help them stay healthy',
    dayInLife: 'Examine animals, diagnose conditions, perform surgeries, and educate pet owners. You work with various animals, from pets to farm animals, combining medical knowledge with compassion.',
    skillSignals: ['SOCIAL_EMOTIONAL', 'ATTENTION', 'COGNITIVE_REASONING'],
    recommendedSubjects: ['Biology', 'Chemistry', 'Animal Science'],
    starterPathSteps: ['Study animal science', 'Veterinary school', 'Get licensed'],
    icon: '🐾',
    rarityTier: 'EMERGING',
  },
  {
    id: 'photographer',
    title: 'Photographer',
    shortPitch: 'Capture moments and tell stories through images',
    dayInLife: 'Plan photo shoots, work with clients, edit photos, and build your portfolio. You might specialize in portraits, events, nature, or commercial photography. Every shot is a creative opportunity.',
    skillSignals: ['CREATIVITY', 'ATTENTION'],
    recommendedSubjects: ['Art', 'Photography', 'Business'],
    starterPathSteps: ['Learn photography basics', 'Practice regularly', 'Build a portfolio'],
    icon: '📷',
    rarityTier: 'COMMON',
  },
  {
    id: 'social_worker',
    title: 'Social Worker',
    shortPitch: 'Support individuals and communities to overcome challenges',
    dayInLife: 'Meet with clients, assess needs, connect people with resources, and advocate for change. You work in schools, hospitals, or community centers, helping people navigate difficult situations.',
    skillSignals: ['SOCIAL_EMOTIONAL', 'LANGUAGE', 'METACOGNITION'],
    recommendedSubjects: ['Social Work', 'Psychology', 'Sociology'],
    starterPathSteps: ['Get a social work degree', 'Complete internships', 'Get licensed'],
    icon: '🤝',
    rarityTier: 'COMMON',
  },
  {
    id: 'athlete',
    title: 'Professional Athlete',
    shortPitch: 'Compete at the highest level and inspire others',
    dayInLife: 'Train daily, practice skills, compete in games or matches, and maintain peak physical condition. You work with coaches, study opponents, and constantly push your limits.',
    skillSignals: ['ATTENTION', 'PLANNING', 'METACOGNITION'],
    recommendedSubjects: ['Physical Education', 'Your sport', 'Nutrition'],
    starterPathSteps: ['Train consistently', 'Compete at higher levels', 'Get noticed'],
    icon: '🏃',
    rarityTier: 'ADVANCED',
  },
  {
    id: 'nurse',
    title: 'Nurse',
    shortPitch: 'Provide compassionate care and support healing',
    dayInLife: 'Check on patients, administer medications, assist doctors, and provide emotional support. You work in hospitals, clinics, or homes, helping people through their health journey.',
    skillSignals: ['SOCIAL_EMOTIONAL', 'ATTENTION', 'PLANNING'],
    recommendedSubjects: ['Biology', 'Chemistry', 'Health Sciences'],
    starterPathSteps: ['Nursing school', 'Get licensed', 'Gain experience'],
    icon: '💉',
    rarityTier: 'COMMON',
  },
  {
    id: 'journalist',
    title: 'Journalist',
    shortPitch: 'Investigate, inform, and hold truth to power',
    dayInLife: 'Research stories, conduct interviews, write articles, and report news. You might work for newspapers, TV, or online media, covering local events or global issues.',
    skillSignals: ['LANGUAGE', 'COGNITIVE_REASONING', 'ATTENTION'],
    recommendedSubjects: ['Journalism', 'English', 'Political Science'],
    starterPathSteps: ['Study journalism', 'Write for school publications', 'Build a portfolio'],
    icon: '📰',
    rarityTier: 'COMMON',
  },
  {
    id: 'environmental_scientist',
    title: 'Environmental Scientist',
    shortPitch: 'Protect our planet and find sustainable solutions',
    dayInLife: 'Study ecosystems, analyze environmental data, conduct field research, and develop conservation strategies. You work to understand and protect natural environments.',
    skillSignals: ['COGNITIVE_REASONING', 'PLANNING', 'ATTENTION'],
    recommendedSubjects: ['Biology', 'Chemistry', 'Environmental Science'],
    starterPathSteps: ['Study environmental science', 'Complete field research', 'Get certified'],
    icon: '🌱',
    rarityTier: 'EMERGING',
  },
  {
    id: 'game_designer',
    title: 'Game Designer',
    shortPitch: 'Create interactive experiences that entertain and engage',
    dayInLife: 'Design game mechanics, create levels, write stories, and test gameplay. You work with artists and programmers to bring game worlds to life, balancing fun with challenge.',
    skillSignals: ['CREATIVITY', 'PLANNING', 'COGNITIVE_REASONING'],
    recommendedSubjects: ['Game Design', 'Computer Science', 'Art'],
    starterPathSteps: ['Learn game design', 'Create small games', 'Build a portfolio'],
    icon: '🎮',
    rarityTier: 'EMERGING',
  },
  {
    id: 'therapist',
    title: 'Therapist',
    shortPitch: 'Help people heal and grow through therapeutic support',
    dayInLife: 'Conduct therapy sessions, listen to clients, develop treatment plans, and provide emotional support. You help people work through challenges and develop coping strategies.',
    skillSignals: ['SOCIAL_EMOTIONAL', 'METACOGNITION', 'LANGUAGE'],
    recommendedSubjects: ['Psychology', 'Counseling', 'Social Work'],
    starterPathSteps: ['Get a counseling degree', 'Complete training', 'Get licensed'],
    icon: '💚',
    rarityTier: 'COMMON',
  },
  {
    id: 'pilot',
    title: 'Pilot',
    shortPitch: 'Soar through the skies and connect the world',
    dayInLife: 'Pre-flight checks, navigate flights, communicate with air traffic control, and ensure passenger safety. You might fly commercial planes, cargo, or private aircraft.',
    skillSignals: ['ATTENTION', 'PLANNING', 'COGNITIVE_REASONING'],
    recommendedSubjects: ['Mathematics', 'Physics', 'Aviation'],
    starterPathSteps: ['Flight training', 'Get pilot license', 'Build flight hours'],
    icon: '✈️',
    rarityTier: 'ADVANCED',
  },
  {
    id: 'animator',
    title: 'Animator',
    shortPitch: 'Bring characters and stories to life through animation',
    dayInLife: 'Create character designs, animate scenes, work with storyboards, and collaborate with directors. You might work on movies, TV shows, games, or commercials.',
    skillSignals: ['CREATIVITY', 'ATTENTION', 'PLANNING'],
    recommendedSubjects: ['Art', 'Animation', 'Computer Graphics'],
    starterPathSteps: ['Learn animation software', 'Create demo reels', 'Build a portfolio'],
    icon: '🎬',
    rarityTier: 'EMERGING',
  },
  {
    id: 'marine_biologist',
    title: 'Marine Biologist',
    shortPitch: 'Explore ocean life and protect marine ecosystems',
    dayInLife: 'Study marine organisms, conduct research, dive in oceans, and analyze data. You might work in labs, on research vessels, or in aquariums, studying everything from tiny plankton to whales.',
    skillSignals: ['COGNITIVE_REASONING', 'ATTENTION', 'PLANNING'],
    recommendedSubjects: ['Biology', 'Chemistry', 'Marine Science'],
    starterPathSteps: ['Study marine biology', 'Complete research projects', 'Get certified'],
    icon: '🐋',
    rarityTier: 'ADVANCED',
  },
  {
    id: 'chef_patissier',
    title: 'Pastry Chef',
    shortPitch: 'Create sweet masterpieces that delight the senses',
    dayInLife: 'Bake pastries, decorate cakes, develop recipes, and manage dessert menus. You combine precision with artistry, creating beautiful and delicious treats.',
    skillSignals: ['CREATIVITY', 'ATTENTION', 'PLANNING'],
    recommendedSubjects: ['Culinary Arts', 'Chemistry', 'Art'],
    starterPathSteps: ['Culinary school', 'Specialize in pastry', 'Work in bakeries'],
    icon: '🍰',
    rarityTier: 'EMERGING',
  },
  {
    id: 'urban_planner',
    title: 'Urban Planner',
    shortPitch: 'Design cities and communities for better living',
    dayInLife: 'Plan city layouts, analyze data, work with communities, and design sustainable spaces. You balance growth with environmental protection, creating livable cities.',
    skillSignals: ['PLANNING', 'COGNITIVE_REASONING', 'CREATIVITY'],
    recommendedSubjects: ['Geography', 'Urban Planning', 'Environmental Science'],
    starterPathSteps: ['Study urban planning', 'Complete internships', 'Get certified'],
    icon: '🏙️',
    rarityTier: 'EMERGING',
  },
  {
    id: 'astronomer',
    title: 'Astronomer',
    shortPitch: 'Explore the universe and unlock cosmic mysteries',
    dayInLife: 'Observe celestial objects, analyze data, use telescopes, and publish research. You study stars, planets, galaxies, and the fundamental nature of the universe.',
    skillSignals: ['COGNITIVE_REASONING', 'ATTENTION', 'PLANNING'],
    recommendedSubjects: ['Physics', 'Mathematics', 'Astronomy'],
    starterPathSteps: ['Study astronomy', 'Complete research', 'Get a PhD'],
    icon: '🔭',
    rarityTier: 'FRONTIER',
  },
  {
    id: 'forensic_scientist',
    title: 'Forensic Scientist',
    shortPitch: 'Solve mysteries using science and evidence',
    dayInLife: 'Analyze evidence, conduct lab tests, write reports, and testify in court. You work with law enforcement, using scientific methods to help solve crimes.',
    skillSignals: ['COGNITIVE_REASONING', 'ATTENTION', 'PLANNING'],
    recommendedSubjects: ['Chemistry', 'Biology', 'Criminal Justice'],
    starterPathSteps: ['Study forensic science', 'Complete lab training', 'Get certified'],
    icon: '🔍',
    rarityTier: 'ADVANCED',
  },
  {
    id: 'translator',
    title: 'Translator',
    shortPitch: 'Bridge languages and connect cultures',
    dayInLife: 'Translate documents, interpret conversations, and help people communicate across languages. You might work with books, legal documents, or live events.',
    skillSignals: ['LANGUAGE', 'ATTENTION', 'METACOGNITION'],
    recommendedSubjects: ['Languages', 'Literature', 'Cultural Studies'],
    starterPathSteps: ['Master multiple languages', 'Get certified', 'Build experience'],
    icon: '🌐',
    rarityTier: 'COMMON',
  },
  {
    id: 'mechanical_engineer',
    title: 'Mechanical Engineer',
    shortPitch: 'Design and build machines that make life easier',
    dayInLife: 'Design mechanical systems, test prototypes, analyze performance, and solve engineering problems. You might work on cars, robots, or manufacturing equipment.',
    skillSignals: ['COGNITIVE_REASONING', 'PLANNING', 'CREATIVITY'],
    recommendedSubjects: ['Mathematics', 'Physics', 'Engineering'],
    starterPathSteps: ['Get an engineering degree', 'Complete internships', 'Get licensed'],
    icon: '⚙️',
    rarityTier: 'COMMON',
  },
  {
    id: 'yoga_instructor',
    title: 'Yoga Instructor',
    shortPitch: 'Guide others on a journey of physical and mental wellness',
    dayInLife: 'Lead yoga classes, create sequences, help students with poses, and maintain your own practice. You help people find balance, strength, and peace through movement.',
    skillSignals: ['SOCIAL_EMOTIONAL', 'METACOGNITION', 'ATTENTION'],
    recommendedSubjects: ['Yoga', 'Anatomy', 'Wellness'],
    starterPathSteps: ['Complete yoga teacher training', 'Get certified', 'Start teaching'],
    icon: '🧘',
    rarityTier: 'COMMON',
  },
  {
    id: 'product_manager',
    title: 'Product Manager',
    shortPitch: 'Shape products that millions of people use',
    dayInLife: 'Meet with teams, prioritize features, analyze user data, and make decisions about product direction. You balance user needs, business goals, and technical constraints.',
    skillSignals: ['PLANNING', 'COGNITIVE_REASONING', 'LANGUAGE'],
    recommendedSubjects: ['Business', 'Computer Science', 'Psychology'],
    starterPathSteps: ['Learn product management basics', 'Build a product portfolio', 'Get certified'],
    icon: '📱',
    rarityTier: 'EMERGING',
  },
  {
    id: 'marketing_specialist',
    title: 'Marketing Specialist',
    shortPitch: 'Connect brands with people through creative campaigns',
    dayInLife: 'Create marketing strategies, design campaigns, analyze data, and engage with audiences. You might work on social media, content, or advertising.',
    skillSignals: ['CREATIVITY', 'LANGUAGE', 'SOCIAL_EMOTIONAL'],
    recommendedSubjects: ['Marketing', 'Communication', 'Business'],
    starterPathSteps: ['Study marketing', 'Build campaigns', 'Get experience'],
    icon: '📢',
    rarityTier: 'COMMON',
  },
  {
    id: 'financial_analyst',
    title: 'Financial Analyst',
    shortPitch: 'Help businesses make smart financial decisions',
    dayInLife: 'Analyze financial data, create reports, forecast trends, and advise on investments. You work with numbers to understand business performance.',
    skillSignals: ['COGNITIVE_REASONING', 'ATTENTION', 'PLANNING'],
    recommendedSubjects: ['Mathematics', 'Economics', 'Business'],
    starterPathSteps: ['Study finance', 'Get certified', 'Gain experience'],
    icon: '💰',
    rarityTier: 'COMMON',
  },
  {
    id: 'event_planner',
    title: 'Event Planner',
    shortPitch: 'Create memorable experiences and bring people together',
    dayInLife: 'Plan events, coordinate vendors, manage budgets, and ensure everything runs smoothly. You might organize weddings, conferences, or celebrations.',
    skillSignals: ['PLANNING', 'CREATIVITY', 'SOCIAL_EMOTIONAL'],
    recommendedSubjects: ['Business', 'Hospitality', 'Communication'],
    starterPathSteps: ['Learn event planning', 'Plan small events', 'Build a portfolio'],
    icon: '🎉',
    rarityTier: 'COMMON',
  },
  {
    id: 'fitness_trainer',
    title: 'Fitness Trainer',
    shortPitch: 'Help people achieve their health and fitness goals',
    dayInLife: 'Design workout programs, train clients, demonstrate exercises, and motivate people. You help others build strength, endurance, and confidence.',
    skillSignals: ['SOCIAL_EMOTIONAL', 'ATTENTION', 'PLANNING'],
    recommendedSubjects: ['Physical Education', 'Nutrition', 'Anatomy'],
    starterPathSteps: ['Get fitness certification', 'Gain experience', 'Build client base'],
    icon: '💪',
    rarityTier: 'COMMON',
  },
  {
    id: 'interior_designer',
    title: 'Interior Designer',
    shortPitch: 'Transform spaces into beautiful and functional environments',
    dayInLife: 'Meet with clients, create design plans, select materials, and oversee installations. You combine aesthetics with functionality to create inspiring spaces.',
    skillSignals: ['CREATIVITY', 'PLANNING', 'ATTENTION'],
    recommendedSubjects: ['Art', 'Design', 'Architecture'],
    starterPathSteps: ['Study interior design', 'Build a portfolio', 'Get licensed'],
    icon: '🏠',
    rarityTier: 'COMMON',
  },
  {
    id: 'biomedical_engineer',
    title: 'Biomedical Engineer',
    shortPitch: 'Combine engineering and medicine to improve healthcare',
    dayInLife: 'Design medical devices, develop prosthetics, create diagnostic tools, and work with healthcare professionals. You use technology to save and improve lives.',
    skillSignals: ['COGNITIVE_REASONING', 'PLANNING', 'ATTENTION'],
    recommendedSubjects: ['Biology', 'Engineering', 'Mathematics'],
    starterPathSteps: ['Study biomedical engineering', 'Complete internships', 'Get certified'],
    icon: '🏥',
    rarityTier: 'ADVANCED',
  },
  {
    id: 'content_creator',
    title: 'Content Creator',
    shortPitch: 'Share your passion and creativity with the world',
    dayInLife: 'Create videos, write posts, engage with audiences, and build your brand. You might focus on education, entertainment, or lifestyle content.',
    skillSignals: ['CREATIVITY', 'LANGUAGE', 'SOCIAL_EMOTIONAL'],
    recommendedSubjects: ['Media', 'Communication', 'Your passion area'],
    starterPathSteps: ['Choose your niche', 'Create content regularly', 'Build your audience'],
    icon: '🎥',
    rarityTier: 'COMMON',
  },
  {
    id: 'research_scientist',
    title: 'Research Scientist',
    shortPitch: 'Push the boundaries of human knowledge',
    dayInLife: 'Design experiments, collect data, analyze results, and publish findings. You work in labs or field settings, contributing to scientific advancement.',
    skillSignals: ['COGNITIVE_REASONING', 'ATTENTION', 'PLANNING'],
    recommendedSubjects: ['Your field of science', 'Mathematics', 'Statistics'],
    starterPathSteps: ['Get a science degree', 'Complete research projects', 'Publish findings'],
    icon: '🔬',
    rarityTier: 'ADVANCED',
  },
  {
    id: 'humanitarian_worker',
    title: 'Humanitarian Worker',
    shortPitch: 'Make a difference in communities around the world',
    dayInLife: 'Provide aid, coordinate relief efforts, work with communities, and advocate for those in need. You help people during crises and support long-term development.',
    skillSignals: ['SOCIAL_EMOTIONAL', 'CHARACTER_VALUES', 'LANGUAGE'],
    recommendedSubjects: ['International Relations', 'Social Work', 'Languages'],
    starterPathSteps: ['Volunteer locally', 'Get relevant education', 'Join organizations'],
    icon: '🌍',
    rarityTier: 'ADVANCED',
  },
  {
    id: 'robotics_engineer',
    title: 'Robotics Engineer',
    shortPitch: 'Build intelligent machines that work alongside humans',
    dayInLife: 'Design robots, program AI systems, test prototypes, and solve complex engineering challenges. You create machines that can see, think, and act.',
    skillSignals: ['COGNITIVE_REASONING', 'PLANNING', 'CREATIVITY'],
    recommendedSubjects: ['Engineering', 'Computer Science', 'Mathematics'],
    starterPathSteps: ['Study robotics', 'Build projects', 'Get experience'],
    icon: '🤖',
    rarityTier: 'FRONTIER',
  },
  {
    id: 'sustainability_consultant',
    title: 'Sustainability Consultant',
    shortPitch: 'Help organizations become more environmentally responsible',
    dayInLife: 'Assess environmental impact, develop sustainability strategies, implement green practices, and measure results. You help businesses reduce their footprint.',
    skillSignals: ['PLANNING', 'COGNITIVE_REASONING', 'CHARACTER_VALUES'],
    recommendedSubjects: ['Environmental Science', 'Business', 'Engineering'],
    starterPathSteps: ['Study sustainability', 'Get certified', 'Build expertise'],
    icon: '♻️',
    rarityTier: 'EMERGING',
  },
  {
    id: 'speech_therapist',
    title: 'Speech Therapist',
    shortPitch: 'Help people communicate effectively and confidently',
    dayInLife: 'Assess speech and language needs, develop treatment plans, work with clients, and track progress. You help people overcome communication challenges.',
    skillSignals: ['LANGUAGE', 'SOCIAL_EMOTIONAL', 'METACOGNITION'],
    recommendedSubjects: ['Speech Therapy', 'Psychology', 'Linguistics'],
    starterPathSteps: ['Get a speech therapy degree', 'Complete clinical training', 'Get licensed'],
    icon: '🗣️',
    rarityTier: 'COMMON',
  },
  {
    id: 'quantum_physicist',
    title: 'Quantum Physicist',
    shortPitch: 'Explore the fundamental nature of reality',
    dayInLife: 'Conduct experiments, develop theories, use advanced mathematics, and publish research. You study the smallest particles and the most fundamental forces.',
    skillSignals: ['COGNITIVE_REASONING', 'ATTENTION', 'PLANNING'],
    recommendedSubjects: ['Physics', 'Mathematics', 'Computer Science'],
    starterPathSteps: ['Study physics', 'Complete research', 'Get a PhD'],
    icon: '⚛️',
    rarityTier: 'FRONTIER',
  },
  {
    id: 'ethical_hacker',
    title: 'Ethical Hacker',
    shortPitch: 'Protect digital systems by thinking like an attacker',
    dayInLife: 'Test security systems, find vulnerabilities, write reports, and help organizations strengthen their defenses. You use hacking skills for good.',
    skillSignals: ['COGNITIVE_REASONING', 'ATTENTION', 'CHARACTER_VALUES'],
    recommendedSubjects: ['Computer Science', 'Cybersecurity', 'Ethics'],
    starterPathSteps: ['Learn cybersecurity', 'Get certified', 'Build experience'],
    icon: '🛡️',
    rarityTier: 'EMERGING',
  },
  {
    id: 'wildlife_photographer',
    title: 'Wildlife Photographer',
    shortPitch: 'Capture the beauty and wonder of the natural world',
    dayInLife: 'Travel to remote locations, wait for perfect moments, capture stunning images, and share stories. You document wildlife and raise awareness about conservation.',
    skillSignals: ['CREATIVITY', 'ATTENTION', 'CHARACTER_VALUES'],
    recommendedSubjects: ['Photography', 'Biology', 'Environmental Science'],
    starterPathSteps: ['Learn photography', 'Practice in nature', 'Build a portfolio'],
    icon: '🦁',
    rarityTier: 'ADVANCED',
  },
  {
    id: 'neuroscientist',
    title: 'Neuroscientist',
    shortPitch: 'Unlock the mysteries of the human brain',
    dayInLife: 'Study brain function, conduct experiments, analyze data, and publish research. You explore how the brain works, learns, and adapts.',
    skillSignals: ['COGNITIVE_REASONING', 'ATTENTION', 'METACOGNITION'],
    recommendedSubjects: ['Biology', 'Psychology', 'Neuroscience'],
    starterPathSteps: ['Study neuroscience', 'Complete research', 'Get a PhD'],
    icon: '🧠',
    rarityTier: 'FRONTIER',
  },
  {
    id: 'sports_coach',
    title: 'Sports Coach',
    shortPitch: 'Develop athletes and build winning teams',
    dayInLife: 'Plan training sessions, teach techniques, motivate players, and develop strategies. You help athletes reach their potential and teams achieve success.',
    skillSignals: ['SOCIAL_EMOTIONAL', 'PLANNING', 'ATTENTION'],
    recommendedSubjects: ['Physical Education', 'Sports Science', 'Psychology'],
    starterPathSteps: ['Get coaching certification', 'Gain experience', 'Build your reputation'],
    icon: '⚽',
    rarityTier: 'COMMON',
  },
  {
    id: 'industrial_designer',
    title: 'Industrial Designer',
    shortPitch: 'Design products that people use every day',
    dayInLife: 'Sketch ideas, create prototypes, test designs, and work with manufacturers. You design everything from phones to furniture, balancing form and function.',
    skillSignals: ['CREATIVITY', 'PLANNING', 'COGNITIVE_REASONING'],
    recommendedSubjects: ['Design', 'Engineering', 'Art'],
    starterPathSteps: ['Study industrial design', 'Build a portfolio', 'Get experience'],
    icon: '📐',
    rarityTier: 'COMMON',
  },
  {
    id: 'cryptographer',
    title: 'Cryptographer',
    shortPitch: 'Protect information using the power of mathematics',
    dayInLife: 'Design encryption systems, analyze security, develop algorithms, and protect digital communications. You use math to keep information safe.',
    skillSignals: ['COGNITIVE_REASONING', 'ATTENTION', 'PLANNING'],
    recommendedSubjects: ['Mathematics', 'Computer Science', 'Cryptography'],
    starterPathSteps: ['Study cryptography', 'Get certified', 'Build expertise'],
    icon: '🔐',
    rarityTier: 'FRONTIER',
  },
  {
    id: 'art_therapist',
    title: 'Art Therapist',
    shortPitch: 'Use creativity to help people heal and grow',
    dayInLife: 'Guide clients through art activities, observe their work, facilitate discussions, and help them process emotions. You use art as a tool for healing.',
    skillSignals: ['CREATIVITY', 'SOCIAL_EMOTIONAL', 'METACOGNITION'],
    recommendedSubjects: ['Art', 'Psychology', 'Therapy'],
    starterPathSteps: ['Study art therapy', 'Complete training', 'Get licensed'],
    icon: '🎨',
    rarityTier: 'EMERGING',
  },
];

/**
 * Get career by ID
 */
export function getCareerById(careerId: string): CareerData | undefined {
  return CAREER_CATALOG.find(career => career.id === careerId);
}

/**
 * Get careers by skill signals
 */
export function getCareersBySkillSignals(skillSignals: string[]): CareerData[] {
  return CAREER_CATALOG.filter(career =>
    career.skillSignals.some(signal => skillSignals.includes(signal))
  );
}

/**
 * Get all careers
 */
export function getAllCareers(): CareerData[] {
  return CAREER_CATALOG;
}

